In [1]:
import torch
import torch.nn as nn
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [5]:
df.shape

(569, 31)

In [6]:
df.head()

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.isna().sum()

diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [7]:
X = df.drop(columns=['diagnosis'])
y = df['diagnosis']

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
X_train

     radius_mean  texture_mean  ...  symmetry_worst  fractal_dimension_worst
68         9.029         17.33  ...          0.4228                  0.11750
181       21.090         26.57  ...          0.4098                  0.12840
63         9.173         13.86  ...          0.3282                  0.08490
248       10.650         25.22  ...          0.3409                  0.08147
60        10.170         14.88  ...          0.3557                  0.08020
..           ...           ...  ...             ...                      ...
71         8.888         14.64  ...          0.2254                  0.10840
106       11.640         18.33  ...          0.2806                  0.09097
270       14.290         16.82  ...          0.2458                  0.06120
435       13.980         19.62  ...          0.3179                  0.10550
102       12.180         20.52  ...          0.2694                  0.06878

[455 rows x 30 columns]

In [20]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [21]:
X_train_scaled.shape

(455, 30)

In [12]:
X_test.shape

(114, 30)

In [18]:
y_train

68     B
181    M
63     B
248    B
60     B
      ..
71     B
106    B
270    B
435    M
102    B
Name: diagnosis, Length: 455, dtype: object

In [17]:
y_test.unique()

array(['B', 'M'], dtype=object)

In [19]:
from sklearn.preprocessing import LabelEncoder

In [22]:
label = LabelEncoder()

y_train_scaled = label.fit_transform(y_train)
y_test_scaled = label.transform(y_test)

In [24]:
y_test_scaled

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1])

In [37]:
X_train_tensor = torch.from_numpy(X_train_scaled)
X_test_tensor = torch.from_numpy(X_test_scaled)
y_train_tensor = torch.from_numpy(y_train_scaled)
y_test_tensor = torch.from_numpy(y_test_scaled)

In [43]:
X_train_tensor = X_train_tensor.float()
y_train_tensor = y_train_tensor.float()

In [45]:
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()

    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)
    return out

In [46]:
loss_function = nn.BCELoss()

In [48]:
print(type(loss_function))

<class 'torch.nn.modules.loss.BCELoss'>

In [51]:
model = Model(X_train_tensor.shape[1])

optimizer = torch.optim.SGD(model.parameters(), lr = 0.1)

for epoch in range(24):

  y_pred = model(X_train_tensor)    # forward pass
  loss = loss_function(y_pred,y_train_tensor.view(-1,1))    # loss calculate

  optimizer.zero_grad()  # clear gradients

  loss.backward()    # backward pass

  optimizer.step()     # parameters update
  print(f'Epoch-{epoch}, Loss-{loss.item()}')

Epoch-0, Loss-0.715323269367218
Epoch-1, Loss-0.6872472763061523
Epoch-2, Loss-0.6628510355949402
Epoch-3, Loss-0.6424514651298523
Epoch-4, Loss-0.6256815195083618
Epoch-5, Loss-0.6115991473197937
Epoch-6, Loss-0.5976863503456116
Epoch-7, Loss-0.585122287273407
Epoch-8, Loss-0.5737406015396118
Epoch-9, Loss-0.5628230571746826
Epoch-10, Loss-0.5523468852043152
Epoch-11, Loss-0.5424073934555054
Epoch-12, Loss-0.5329686999320984
Epoch-13, Loss-0.5241518616676331
Epoch-14, Loss-0.5157033801078796
Epoch-15, Loss-0.5075936317443848
Epoch-16, Loss-0.49983909726142883
Epoch-17, Loss-0.492431640625
Epoch-18, Loss-0.48537033796310425
Epoch-19, Loss-0.4786337614059448
Epoch-20, Loss-0.472181111574173
Epoch-21, Loss-0.4660293459892273
Epoch-22, Loss-0.4601186215877533
Epoch-23, Loss-0.4544547200202942

In [54]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor.float())
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6228070259094238